################################################################################
#
# plot_nmds.R
#
# Here we take in the *.nmds.axes file from the mouse stability analysis and
# plot it in R as we did in Figure 4 of Kozich et al.
#
# Dependencies:   2-D axes file generated by the nmds command in mothur
# Produces:       results/figures/nmds_figure.png
#
################################################################################

library(dplyr)
library(ggplot2)
plot_nmds <- function (axes_file){
  axes <- read.table(file=axes_file, header=T, row.names=1) %>%
                        mutate(day = as.numeric(gsub(".*D(\\d*)$", "\\1", rownames(.)))) %>%
                        mutate(early_late = ifelse(day <= 10, "early", ifelse(day>=140 & day <=150, "late", NA))) %>%
                        filter(!is.na(early_late))
    ggplot(axes) +
        aes(x=axis1, y=axis2, pch=early_late, col=early_late) +
        geom_point(pch=19) +
        labs(x="NMDS Axis 1", y="NMDS Axis 2") +
        scale_color_brewer(palette="Set1", labels=c("Early", "Late"), name=NULL) +
        theme_classic() +
            theme(legend.background = element_rect(size=0.5, linetype="solid", color="black"),
                        legend.text = element_text(size=12),
                        legend.position = c(0.75,0.15),
                        axis.title = element_text(size=14),
                        axis.text = element_text(size=12),
                        panel.border = element_rect(colour = "black", fill=NA, size=1)
            ) +
        ggsave("results/figures/nmds_figure.png")
}
